### ISSUE TITLE
关于PostJson 方法的使用问题

### ISSUE THREAD

**Issue by fengziadmin** [kexin8/teambition-sdk-go#3]
PostJson 的使用问题。

**Comment by fengziadmin** [comment]
![image](https://user-images.githubusercontent.com/5696815/227735464-8e67a9dd-c2c3-4fc2-9fb4-b601b516644c.png)
![image](https://user-images.githubusercontent.com/5696815/227735484-93d8cd52-5a5a-45ed-ac27-9fbec2d9c226.png)

**Comment by fengziadmin** [comment]
将task 类的 UniqueID string类型修改 int64  问题解决。

**Comment by kexin8** [comment]
感谢参与贡献，目前tb上开放的接口部分接口我也没有用到，所以可能会出现部分问题
